$background = rgb({{background | strip}})
$foreground = rgb({{foreground | strip}})
$primary = rgb({{color4 | strip}})
$secondary = rgb({{color5 | strip}})
$tertiary = rgb({{color6 | strip}})
$error = rgb({{color1 | strip}})
$surface = rgb({{color0 | strip}})
$outline = rgb({{color8 | strip}})
