[config]
reload_apps = false

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/current-theme.conf"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"
